name: Bandit Linter for Python
description: Run bandit security linter on given target or default.

inputs:
  target:
    description: Target for bandit scan.
    required: false
    default: src/

runs:
  using: "composite"

  steps:
    - name: Bandit
      shell: bash
      run: |
        source .venv/bin/activate
        bandit -r ${{inputs.target}}
